<a href="https://colab.research.google.com/github/shr968/marvel/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

small_array = np.array([[1, 2], [3, 4]])

tiled_array = np.tile(small_array, (3, 2))

print("Tiled Array:")
print(tiled_array)


Tiled Array:
[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]
